### ISSUE TITLE
Adding Certificate Extensions 

### ISSUE THREAD

**Issue by moritz2** [cbaker6/CertificateSigningRequest#12]
Hello,

I'm currently having some trouble to add certificate extensions with subject alternative name.
I don't understand the attributes before my extensions. normally I think they need a ASN.1 code, but they don't have one and it is working...

the ASN.1 code for the certificate extension is: 0x06, 0x02, 0x55, 0x1D and for subject alternative name it is: 0x06, 0x03, 0x55, 0x1D, 0x11.

would be amazing if someone can help me.

Thank you!!

**Comment by wuf810** [comment]
I'm not sure I understand your question. What are you trying to achieve?

**Comment by wuf810** [comment]
Ah sorry I should’ve read your question more thoroughly. Not sure I can help but I’ll have a quick look tomorrow and see what I can learn about request extensions.

**Comment by moritz2** [comment]
Hi @wuf810 have you find a solution? thanks for your support 👍

**Comment by chathuraasanka** [comment]
Hi @moritz2 

Have you found any solution on this, If does can you please provide code sample how to achieve this.

**Comment by cbaker6** [comment]
Adding fields is discussed here: https://github.com/cbaker6/CertificateSigningRequest/issues/9#issuecomment-342913969

You can see the PR that added “emai” here: https://github.com/cbaker6/CertificateSigningRequest/pull/40/commits/41186d0de41de2f35848e957564222d085a18a79

You can begin making the changes and open a PR for help

**Comment by chathuraasanka** [comment]
Hi, @cbaker6

I have attached the changed code with this  Code Line = 226, But the the generated CSR contains a error could you give me help on this 
[CertificateSigningRequest.zip](https://github.com/cbaker6/CertificateSigningRequest/files/6419493/CertificateSigningRequest.zip)

**Comment by cbaker6** [comment]
If you create a pull request (PR) I can review and provide assistance. How to create a pull request can be found here: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by chathuraasanka** [comment]
Hi @cbaker6 

I have created a Pull Request, Could you please review on that

**Comment by raphaelgodro** [comment]
I have the same issue here. I need certificate extensions. The Pull Reuqets is addinf more Subject headers but it seems like certificate extensions must be in a whole new sequence.
