### ISSUE TITLE
Domain=NSOSStatusErrorDomain Code=-50 "Key generation failed

### ISSUE THREAD

**Issue by karthikhappy** [cbaker6/CertificateSigningRequest#15]
Hi I am getting below error when I run in device and simulator,

Error creating keys occured: Error Domain=NSOSStatusErrorDomain Code=-50 "Key generation failed, error -50" UserInfo={NSDescription=Key generation failed, error -50}, keys weren't created

The private key is not generating,

I am using below code,

            if keyAlgorithm.type == KeyAlgorithm.rsa(signatureType: .sha512).type{
                    let access = SecAccessControlCreateWithFlags(kCFAllocatorDefault,
                                                                 kSecAttrAccessibleAlwaysThisDeviceOnly,
                                                                 .privateKeyUsage,
                                                                 nil)!   // Ignore error
                    
                    privateKeyParameters[String(kSecAttrAccessControl)] = access
                }
           
  //Define what type of keys to be generated here
            var parameters: [String: AnyObject] = [
                String(kSecAttrKeyType): keyAlgorithm.secKeyAttrType,
                String(kSecAttrKeySizeInBits): keyAlgorithm.availableKeySizes.last! as AnyObject,
                String(kSecReturnRef): kCFBooleanTrue,
                kSecPublicKeyAttrs as String: publicKeyParameters as AnyObject,
                kSecPrivateKeyAttrs as String: privateKeyParameters as AnyObject,
            ]

**Comment by cbaker6** [comment]
It looks like you may gave setup the key generation wrong, have a look at this method in the test code. You can look in the file to see how it's used, https://github.com/cbaker6/CertificateSigningRequestSwift/blob/460e288156285e910af3181e0298a3aadd7f53a9/Example/Tests/Tests.swift#L190

**Comment by cbaker6** [comment]
@karthikhappy I see your issue, the snippet of code you provided has an error because of your if statement. See my comment below:

```swift
//Change ".rsa" to ".ec", "SecAccessControlCreateWithFlags" is only for EC on secure enclave. If you want to use RSA keys, they will exist outside of the secure enclave and shouldn't enter this block. This is by Apple's design, not the framework itself
if keyAlgorithm.type == KeyAlgorithm.rsa(signatureType: .sha512).type{
    let access = SecAccessControlCreateWithFlags(kCFAllocatorDefault,
                                                             kSecAttrAccessibleAlwaysThisDeviceOnly,
                                                             .privateKeyUsage,
                                                             nil)! 
...
}
```

You can see more here for details https://github.com/cbaker6/CertificateSigningRequestSwift/blob/460e288156285e910af3181e0298a3aadd7f53a9/Example/Tests/Tests.swift#L205
