### ISSUE TITLE
FAILED - CSR has an invalid signature

### ISSUE THREAD

**Issue by LahiruChathuranga** [cbaker6/CertificateSigningRequest#24]
I have tried to create Secure Enclave keys and CSR. This Error was prompted.

Error Domain=NSOSStatusErrorDomain Code=-67808 "EC signature verification failed, no match" UserInfo={NSDescription=EC signature verification failed, no match}

CSR Generation CODE -
let csrBuild1 = csr.build(pubkeyBits!, privateKey: privateKeySec!, publicKey: publicKeySec!)
let certificateRequestB64 = csrBuild1.base64EncodedString()
        let certificateRequestPEM =
        "-----BEGIN CERTIFICATE REQUEST-----\n\(certificateRequestB64)\n-----END CERTIFICATE REQUEST-----\n"

**Comment by cbaker6** [comment]
You probably set your keys up incorrectly, see here: https://github.com/cbaker6/CertificateSigningRequest/issues/15

The test file provides an example to use the enclave correctly: https://github.com/cbaker6/CertificateSigningRequest/blob/0c77ea4cc6cd60043dd077fc61ecb7283d749f6b/Example/Tests/Tests.swift#L31

**Comment by cbaker6** [comment]
This might help you also https://github.com/cbaker6/CertificateSigningRequest/issues/14#issuecomment-620304226

**Comment by LahiruChathuranga** [comment]
> You probably set your keys up incorrectly, see here: #15
> 
> The test file provides an example to use the enclave correctly:
> 
> https://github.com/cbaker6/CertificateSigningRequest/blob/0c77ea4cc6cd60043dd077fc61ecb7283d749f6b/Example/Tests/Tests.swift#L31

Thanks for the reply. I have solved this issue. it was my mistake.
