### ISSUE TITLE
This is not working on macOS for the given public and private keys

### ISSUE THREAD

**Issue by murali238** [cbaker6/CertificateSigningRequest#33]
generated csr on Mac is invalid and gives following error while validating at https://redkestrel.co.uk/products/decoder/
Key Size | WARNING (0 bits)
Signature | FAILED - CSR has an invalid signature

do you have any idea why it is invalid?

**Comment by cbaker6** [comment]
I think it has something to do with how you are creating the keys in keychain. The examples given are for iOS, I believe the process is slightly different macOS. If you create the keys properly then the framework should work.

Issues with generating keys are not issues with this framework

**Comment by murali238** [comment]
I am able to create keys successfully by doing little modification in code and can see those on my keychain app, I am using below code to create keys on macOS,

```
func generateKeysAndStoreInKeychain(_ algorithm: KeyAlgorithm, keySize: Int, tagPrivate: String, tagPublic: String)->(SecKey?,SecKey?){

        let aTagPublic:AnyObject = tagPublic.data(using: .utf8) as AnyObject
        let aTagPrivate:AnyObject = tagPrivate.data(using: .utf8) as AnyObject
        
        let publicKeyParameters: [String: AnyObject] = [
            String(kSecAttrIsPermanent): kCFBooleanTrue,
            String(kSecAttrApplicationTag): aTagPublic,
            String(kSecAttrLabel):"Provisioning.publicKey" as AnyObject,
            String(kSecAttrAccessible): kSecAttrAccessibleAlways,
        ]
        
        var privateKeyParameters: [String: AnyObject] = [
            String(kSecAttrIsPermanent): kCFBooleanTrue,
            String(kSecAttrApplicationTag): aTagPrivate,
            String(kSecAttrLabel):"Provisioning.privateKey" as AnyObject,
            String(kSecAttrAccessible): kSecAttrAccessibleAlways,
        ]
        
        #if !targetEnvironment(simulator)
        //This only works for Secure Enclave consistign of 256 bit key, note, the signatureType is irrelavent for this check
        if algorithm.type == KeyAlgorithm.ec(signatureType: .sha1).type{
            let access = SecAccessControlCreateWithFlags(kCFAllocatorDefault,
                                                         kSecAttrAccessibleAfterFirstUnlock,
                                                         .privateKeyUsage,
                                                         nil)!   // Ignore error
            
            privateKeyParameters[String(kSecAttrAccessControl)] = access
        }
        #endif
        
        //Define what type of keys to be generated here
        var parameters: [String: AnyObject] = [
            String(kSecAttrKeyType): algorithm.secKeyAttrType,
            String(kSecAttrKeySizeInBits): keySize as AnyObject,
            String(kSecReturnRef): kCFBooleanTrue,
            String(kSecPublicKeyAttrs): publicKeyParameters as AnyObject,
            String(kSecPrivateKeyAttrs): privateKeyParameters as AnyObject,
        ]
        
        #if !targetEnvironment(simulator)
        //iOS only allows EC 256 keys to be secured in enclave. This will attempt to allow any EC key in the enclave, assuming iOS will do it outside of the enclave if it doesn't like the key size, note: the signatureType is irrelavent for this check
        if algorithm.type == KeyAlgorithm.ec(signatureType: .sha1).type{
            parameters[String(kSecAttrTokenID)] = kSecAttrTokenIDSecureEnclave
        }
        #endif
        
        //Use Apple Security Framework to generate keys, save them to application keychain
        var error: Unmanaged<CFError>?
        let privateKey = SecKeyCreateRandomKey(parameters as CFDictionary, &error)
        if privateKey == nil{
            print("Error creating keys occured: \(error!.takeRetainedValue() as Error), keys weren't created")
            return (nil,nil)
        }
        
        //Get generated public key
        let query: [String: AnyObject] = [
            String(kSecClass): kSecClassKey,
             String(kSecAttrKeyType): algorithm.secKeyAttrType,
            //String(kSecAttrApplicationTag): tagPublic as AnyObject,
            String(kSecAttrApplicationTag): aTagPublic,
            String(kSecReturnRef): kCFBooleanTrue
        ]
        var publicKeyReturn:AnyObject?
        let result = SecItemCopyMatching(query as CFDictionary, &publicKeyReturn)
        if result != errSecSuccess{
            print("Error getting publicKey fron keychain occured: \(result)")
            return (privateKey,nil)
        }
        let publicKey = publicKeyReturn as! SecKey?
        return (privateKey,publicKey)
    }
```

And it is giving CSR string but that CSR is invalid while I cross check at https://redkestrel.co.uk/products/decoder/

on iOS I don't see any issues, it works perfectly there.

**Comment by murali238** [comment]
Thanks, 

Able to generate a valid csr if i use `SecKeyCopyExternalRepresentation` while sending public key bytes.

**Comment by cbaker6** [comment]
@murali238 thanks for sharing, I will see if I can add your updates into the testcases and readme, unless you see where to add them directly?

**Comment by murali238** [comment]
I have done below two changes on MacOS to generate a valid csr.

1. `kSecAttrApplicationTag` key value as `Data` instead of `String`
2. Replaced `getPublicKeyBits` with below function

```
 func getPublicKeyBits(_ algorithm: KeyAlgorithm, publicKey: SecKey, tagPublic: String)->(Data?,Int?) {
        
        //Set block size
        let keyBlockSize = SecKeyGetBlockSize(publicKey)
        
        //Ask keychain to provide the publicKey in bits
        let query: [String: AnyObject] = [
            String(kSecClass): kSecClassKey,
            String(kSecAttrKeyType): algorithm.secKeyAttrType,
            String(kSecAttrApplicationTag): tagPublic.data(using: .utf8) as AnyObject,
            String(kSecReturnRef): kCFBooleanTrue
        ]
        var tempPublicKeyBits:AnyObject?
        var _ = SecItemCopyMatching(query as CFDictionary, &tempPublicKeyBits)
        
        if tempPublicKeyBits != nil {
            var error:Unmanaged<CFError>? = nil
            guard let keyBits = SecKeyCopyExternalRepresentation(tempPublicKeyBits as! SecKey, &error) else {
                return (nil,nil)
            }
            return (keyBits as Data,keyBlockSize)
        }
        
        return (nil,nil)
    }
```
Hope it helps some one.

**Comment by cbaker6** [comment]
@murali238 I've added your recommendations, but for some reason the keys don't generate when I run the tests, `swift test` from command line.

Was there anything else you added?

The changes I made are here https://github.com/cbaker6/CertificateSigningRequest/blob/064822392f13631164ee649126408b67fd30d667/Tests/CertificateSigningRequestTests/CertificateSigningRequestTests.swift#L551

**Comment by murali238** [comment]
@cbaker6 
instead of  `String(kSecReturnData): kCFBooleanTrue` ,please use `String(kSecReturnRef): kCFBooleanTrue` in the query on macOS

**Comment by cbaker6** [comment]
I tried out your getPublicKeyBits function, but I still got the same errors.

Did you do anything different when creating the keys besides using `query[String(kSecAttrApplicationTag)] = tagPublic.data(using: .utf8) as AnyObject`?

The updated function I have is below: https://github.com/cbaker6/CertificateSigningRequest/blob/f197fe15a03081d9a54a81f479be437d31d096ac/Tests/CertificateSigningRequestTests/CertificateSigningRequestTests.swift#L548-L587


The code to create the keys is below:

https://github.com/cbaker6/CertificateSigningRequest/blob/f197fe15a03081d9a54a81f479be437d31d096ac/Tests/CertificateSigningRequestTests/CertificateSigningRequestTests.swift#L470-L487

**Comment by cbaker6** [comment]
@murali238 you can see the errors in GitHub Actions here under "Build": https://github.com/cbaker6/CertificateSigningRequest/runs/1043401059?check_suite_focus=true

The error code is `-25300`, `Error Domain=NSOSStatusErrorDomain Code=-50 "failed to generate asymmetric keypair" (paramErr: error in user parameter list) UserInfo={NSDescription=failed to generate asymmetric keypair}, keys weren't created`

**Comment by cbaker6** [comment]
It turns out if the keychain parameters are switched to `[String: Any]`, the only thing that needs to be fixed is `String(kSecAttrApplicationTag): tagPublic.data(using: .utf8)!`

This allows interoperability between iOS and macOS.

See the updates here: https://github.com/cbaker6/CertificateSigningRequest/blob/169ba18c273e1e7a4d3166ef707adeac4b9ba007/Tests/CertificateSigningRequestTests/CertificateSigningRequestTests.swift#L543-L563

**Comment by stklieme** [comment]
@murali238, thank you so much. I ran into the same problem on macOS and looked for a solution for weeks. 
The `SecKeyCopyExternalRepresentation` way solved it.

@cbaker6 By the way you can get rid of all the String conversions by bridge casting the type rather than annotating it.
For example

```
      let query = [ 
             kSecClass: kSecClassKey, 
             kSecAttrKeyType: algorithm.secKeyAttrType, 
             kSecAttrApplicationTag: tagPublic.data(using: .utf8)!, 
             kSecReturnData: true 
         ] as [String:Any]
```
