### ISSUE TITLE
Code=-67808 "RSA signature verification failed, no match"

### ISSUE THREAD

**Issue by siswasandi** [cbaker6/CertificateSigningRequest#38]
Hi,

i've used this CertificateSigningRequest to create CSR with rsa 2048 with sha 256.
the CSR was successfully created, but if i using this method to verification signature :

let builtCSR = csr.buildCSRAndReturnString(potentialPublicKeyBits!, privateKey: privateKeys!, publicKey: publicKeys!)

it always return "Code=-67808 "RSA signature verification failed, no match""

is there any idea and how to solve it?

thank you

**Comment by cbaker6** [comment]
Are you able to open a PR and write a test following the examples here https://github.com/cbaker6/CertificateSigningRequest/blob/bc91a6a910143d81a9b8bdaed72675ade6612d76/Tests/CertificateSigningRequestTests/CertificateSigningRequestTests.swift#L82.

Then I will be able to see the problem you are running into.

**Comment by siswasandi** [comment]
oh I've found the problem. 

it always return "Code=-67808 "RSA signature verification failed, no match"",

this is because I generated the key still using the same tag, so the signature is invalid. the solution is if we want to generate a new key, we can use a new tag, or we can delete a key with the previous tag. Is it true?

**Comment by siswasandi** [comment]
and one more thing.

is it possible to add a "description (fill with OID and description in string)" parameter and "email" parameter when generating CSR? because the default parameter is CertificateSigningRequest(commonName: String?, organizationName:String?, organizationUnitName:String?, countryName:String?, stateOrProvinceName:String?, localityName:String?, keyAlgorithm: KeyAlgorithm).

**Comment by cbaker6** [comment]
You are correct about the tags you should see this comment https://github.com/cbaker6/CertificateSigningRequest/issues/14#issuecomment-620304226

**Comment by cbaker6** [comment]
Can you submit a PR for the email? You can see this comment for the OID https://github.com/cbaker6/CertificateSigningRequest/issues/12#issuecomment-396678152

**Comment by siswasandi** [comment]
I want to add the extension E = (email), and description to the certificate. I have checked the OID at https://www.alvestrand.no/objectid/1.2.840.113549.1.9.1.html, the OID is 1.2.840.113549.1.9.1 (hex value = 06 09 2A 86 48 86 F7 0D 01 09 01) for emailAddress. but when I add this OID to CertificateSigningRequest Class:

```
private let OBJECT_emailAddress:[UInt8] = [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x09, 0x01]
private let OBJECT_descriptions:[UInt8] = [0x06, 0x03, 0x55, 0x04, 0x0D]
private let emailAddress:String?
private let descriptions:String?
private let SEQUENCE_tag:UInt8 = 0x30
private let SET_tag:UInt8 = 0x31
```
Add the parameter to init method

```
public init(emailAddress: String?, descriptions: String?, commonName: String?, organizationName:String?, organizationUnitName:String?, countryName:String?, stateOrProvinceName:String?, localityName:String?, keyAlgorithm: KeyAlgorithm){
        self.emailAddress = emailAddress

public convenience override init(){
        self.init(emailAddress: nil, descriptions: nil, commonName: nil, organizationName:nil, organizationUnitName:nil, countryName:nil, stateOrProvinceName:nil, localityName:nil, keyAlgorithm: KeyAlgorithm.rsa(signatureType: .sha512))
    }
    
public convenience init(keyAlgorithm: KeyAlgorithm){
        self.init(emailAddress: nil, descriptions: nil, commonName: nil, organizationName:nil, organizationUnitName:nil, countryName:nil, stateOrProvinceName:nil, localityName:nil, keyAlgorithm: keyAlgorithm)
    }
```

Add and append the email to the buildertificationRequestInfo with : 

```
var subject = Data(capacity: 256)
 if emailAddress != nil{
                   appendingSubjectItem(OBJECT_emailAddress, value: emailAddress!, into: &subject)
               }

 if descriptions != nil {
            appendingSubjectItem(OBJECT_descriptions, value: descriptions!, into: &subject)
        }
```

The description has appeared in the extension successfully, but the email is not showing. how to solve this problem?

**Comment by siswasandi** [comment]
<img width="888" alt="Screen Shot 2020-11-28 at 17 41 12" src="https://user-images.githubusercontent.com/26589807/100511495-31353b80-31a1-11eb-8b22-79114184e79f.png">

**Comment by cbaker6** [comment]
If you create a pull request (PR) I can review and provide assistance. How to create a pull request can be found here: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by siswasandi** [comment]
okay. i've found the problem.

we must set the if conditional in "enclose" function with :

`if what.count != 5 && what.count != 11 {
            print("Error: attempting to a non-subject item")
            return
        }`
because the emailAddress's OID : [UInt8] count is 11.

**Comment by cbaker6** [comment]
I'm opening this back up. Can you commit the problem you fixed to the branch where you committed the PR? If the code passes the tests, your commit will be added to the framework.
