### ISSUE TITLE
CSR max linelength, parsing on macOS

### ISSUE THREAD

**Issue by svenyonson** [cbaker6/CertificateSigningRequest#43]
The base64 body of the CSR is a continuous string, which works fine with some openssl implementations (e.g. linux), but the macOS version barfs because the lines are more than 64 characters. If I manually edit the CSR, adding newlines every 64 characters, macOS openssl can parse the CSR.

**Comment by cbaker6** [comment]
This happens when you use? https://github.com/cbaker6/CertificateSigningRequest/blob/523b7a35eb4725bc5419859a325f8c0b862c00b8/Sources/CertificateSigningRequest/CertificateSigningRequest.swift#L141

Example here: https://github.com/cbaker6/CertificateSigningRequest/blob/523b7a35eb4725bc5419859a325f8c0b862c00b8/Tests/CertificateSigningRequestTests/CertificateSigningRequestTests.swift#L123

**Comment by svenyonson** [comment]
I see. In that case I would need to manually add the BEGIN/END headers? I need it to be in a valid PEM format.

**Comment by cbaker6** [comment]
You shouldn't need to add anything, if you call the `buildCSRAndReturnString` method it does it for you.

**Comment by svenyonson** [comment]
That's what I am calling: 
```
        // Generate CSR Data
        let csr = CertificateSigningRequest(commonName: commonName,
                                            organizationName: organizationName, organizationUnitName: organizationUnitName,
                                            countryName: countryName, stateOrProvinceName: stateOrProvinceName,
                                            localityName: localityName, emailAddress: emailAddress,
                                            description: description, keyAlgorithm: keyAlgorithm)
        // Build the CSR String
        let csrBuild = csr.buildCSRAndReturnString(publicKeyBits, privateKey: privateKey)
        if let csrWithHeaderFooter = csrBuild {
            print(csrWithHeaderFooter)
            assert(csrBuild!.contains("BEGIN"), "CSR string builder isn't complete")
        } else {
            assert(csrBuild != nil, "CSR with header not generated")
        }
        
```

**Comment by svenyonson** [comment]
This what I get: 
```-----BEGIN CERTIFICATE REQUEST-----
MIIC7TCCAdUCAQAwgacxCzAJBgNVBAYMAlVTMQswCQYDVQQIDAJDTzETMBEGA1UEBwwKTG91aXN2aWxsZTESMBAGA1UECgwJQ2FibGVMYWJzMQ4wDAYDVQQLDAVLeXJpbzEfMB0GA1UEAwwWaXdpbnMuY2xpZW50Lmt5cmlvLmNvbTExMC8GA1UEDQwoPElXaU5TX1NESy5fQXV0aGVudGljYXRpb246IDB4MjgzYWNjZTcwPjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK50pjzbepizwbUrRGUp3MpwemwgivT8jyb90+4rF2Ygg5qacP2vk2nAK7EAv3jAzD6Vg4cFlnL5oYuJqOUyG82nbxBXGKaRs81g9/JC9XQeKIIADRQ7XtLFgqktmNxcqWbntJRRK5HOKxwmIXsosPszkGbq31PpGjTQYVSabD8Xz9QavrCq2zkEWEI9WWqCbXhqulXfM//5VRri0tnqzTLLprZ8MnZlIgufT2fkx09SzxW9hHRCnhbfqfMuHgdZLXAZopAvyKqrgliIC26OZfMAY+HPXm7ka4ctbs7CADN7tGusNsyjOm319Ao8usP1C27j0URuyIuw/YaYf+aA9+sCAwEAAaAAMA0GCSqGSIb3DQEBDQUAA4IBAQChtNuSQMtpLX3esiuQeXIZX0nxXLcBQhYEwpp2oAqMFP3+6GAn9gPe3HroFy9npQkfXFxIP9Mz67UMMoxAqceH27/8rHdWTNzSaoFeTHIXWt8HD3Ev16xnTYVWzvje4KIjJXSTJEJr88xjuYc/C3zmF0EP0xkDKjX/qobbUQcNOv3OhZPdtHOBXuLz3mhH6KXrlBO4L7AvnNWgoNgujJqAB030cICOuW97eXZebgt1G6ZGFJ9Wv5IOdKoACyPQL9KXfBMqtP1JdxsRg+JacN4gfRWikuaZt//n1PayxbdhHyx30bhhUeOSIWrLTEnnMnkSUD2Hx70Wd0dHc6ugyqhn
-----END CERTIFICATE REQUEST-----
```

**Comment by cbaker6** [comment]
It seems like you may be doing something wrong. Are you using an older version of the framework?

I just ran the [test suite](https://github.com/cbaker6/CertificateSigningRequest/blob/main/Tests/CertificateSigningRequestTests/CertificateSigningRequestTests.swift) on my Mac and got:

```
-----BEGIN CERTIFICATE REQUEST-----
MIIB9jCB3wIBADCBpDELMAkGA1UEBgwCVVMxCzAJBgNVBAgMAktZMQ0wCwYDVQQH
DARUZXN0MQ0wCwYDVQQKDARUZXN0MQ0wCwYDVQQLDARUZXN0MScwJQYDVQQDDB5D
ZXJ0aWZpY2F0ZVNpZ25pbmdSZXF1ZXN0IFRlc3QxIjAgBgkqhkiG9w0BCQEME25l
dHJlY29uQGNzLnVreS5lZHUxDjAMBgNVBA0MBWhlbGxvMDEwDQYJKoZIhvcNAQEB
BQADIAAwHQIAAhkcow/JEdSEmgAFArUhIgIAAAAAAAAAKgAAoAAwDQYJKoZIhvcN
AQENBQADggEBAJ7Jt9TFoF24kLlFIOo7nECe9WS0exTa5o7/6LnIg1NSfRKv6Q0L
jn1lCRgAy2QkQJ9fn8t+ugMdXkSeCwnQfzG5BU48FdxME/HX5QBR7dy0h82LT/sr
FU4lf2cPPczEhT3h9lL36UHHn071GiQVopsDgkQcKTZ9LBka7iSG1tgTQ46mlsj7
lukN0pmZPXgr95ZZgykI4Giyb4vuQRF6NEs65sWGV/hXU9BRhhWpKAuamw1bXtaC
/g3hvhOUo73gkOAn0ryYpd51nrqDqtV/nuc3nj0OEqugTAiWQuqhFeS1SUGG9VeW
EdgrbLBv5R/h6GiDf8dYsiys2g6/e5nADBA=
-----END CERTIFICATE REQUEST-----
```

You should type `swift test` in the command line and look at your output. If the lines are showing up there correctly, then you are probably calling something incorrectly or something is up with the parameters you are passing in.

**Comment by cbaker6** [comment]
> This what I get:
> 
> ```
> MIIC7TCCAdUCAQAwgacxCzAJBgNVBAYMAlVTMQswCQYDVQQIDAJDTzETMBEGA1UEBwwKTG91aXN2aWxsZTESMBAGA1UECgwJQ2FibGVMYWJzMQ4wDAYDVQQLDAVLeXJpbzEfMB0GA1UEAwwWaXdpbnMuY2xpZW50Lmt5cmlvLmNvbTExMC8GA1UEDQwoPElXaU5TX1NESy5fQXV0aGVudGljYXRpb246IDB4MjgzYWNjZTcwPjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK50pjzbepizwbUrRGUp3MpwemwgivT8jyb90+4rF2Ygg5qacP2vk2nAK7EAv3jAzD6Vg4cFlnL5oYuJqOUyG82nbxBXGKaRs81g9/JC9XQeKIIADRQ7XtLFgqktmNxcqWbntJRRK5HOKxwmIXsosPszkGbq31PpGjTQYVSabD8Xz9QavrCq2zkEWEI9WWqCbXhqulXfM//5VRri0tnqzTLLprZ8MnZlIgufT2fkx09SzxW9hHRCnhbfqfMuHgdZLXAZopAvyKqrgliIC26OZfMAY+HPXm7ka4ctbs7CADN7tGusNsyjOm319Ao8usP1C27j0URuyIuw/YaYf+aA9+sCAwEAAaAAMA0GCSqGSIb3DQEBDQUAA4IBAQChtNuSQMtpLX3esiuQeXIZX0nxXLcBQhYEwpp2oAqMFP3+6GAn9gPe3HroFy9npQkfXFxIP9Mz67UMMoxAqceH27/8rHdWTNzSaoFeTHIXWt8HD3Ev16xnTYVWzvje4KIjJXSTJEJr88xjuYc/C3zmF0EP0xkDKjX/qobbUQcNOv3OhZPdtHOBXuLz3mhH6KXrlBO4L7AvnNWgoNgujJqAB030cICOuW97eXZebgt1G6ZGFJ9Wv5IOdKoACyPQL9KXfBMqtP1JdxsRg+JacN4gfRWikuaZt//n1PayxbdhHyx30bhhUeOSIWrLTEnnMnkSUD2Hx70Wd0dHc6ugyqhn
> -----END CERTIFICATE REQUEST-----
> ```

This doesn't contain `BEGIN`, something isn't generating correctly in your cert or your parameters are incorrect.

**Comment by svenyonson** [comment]
(my paste somehow missed the BEGIN line..)

I am running this on iOS, with Swift 5, and I had to make this change for the newer version:

**Comment by svenyonson** [comment]
```
    public func buildAndEncodeDataAsString(_ publicKeyBits: Data, privateKey: SecKey,
                                           publicKey: SecKey?=nil) -> String? {

        guard let buildData = self.build(publicKeyBits, privateKey: privateKey, publicKey: publicKey) else {
            return nil
        }

        //return buildData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0))
        //    .addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed)
        
        return buildData.base64EncodedString(options: Data.Base64EncodingOptions(rawValue: 0)).addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed)

    }

```

**Comment by cbaker6** [comment]
I ran it for iOS, and have no issues either. You can run the test suite in the Xcode project for iOS as well.

**Comment by svenyonson** [comment]
I'll try the paste again: 
```
-----BEGIN CERTIFICATE REQUEST-----
MIIC7TCCAdUCAQAwgacxCzAJBgNVBAYMAlVTMQswCQYDVQQIDAJDTzETMBEGA1UEBwwKTG91aXN2aWxsZTESMBAGA1UECgwJQ2FibGVMYWJzMQ4wDAYDVQQLDAVLeXJpbzEfMB0GA1UEAwwWaXdpbnMuY2xpZW50Lmt5cmlvLmNvbTExMC8GA1UEDQwoPElXaU5TX1NESy5fQXV0aGVudGljYXRpb246IDB4MjgzYWNjZTcwPjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK50pjzbepizwbUrRGUp3MpwemwgivT8jyb90+4rF2Ygg5qacP2vk2nAK7EAv3jAzD6Vg4cFlnL5oYuJqOUyG82nbxBXGKaRs81g9/JC9XQeKIIADRQ7XtLFgqktmNxcqWbntJRRK5HOKxwmIXsosPszkGbq31PpGjTQYVSabD8Xz9QavrCq2zkEWEI9WWqCbXhqulXfM//5VRri0tnqzTLLprZ8MnZlIgufT2fkx09SzxW9hHRCnhbfqfMuHgdZLXAZopAvyKqrgliIC26OZfMAY+HPXm7ka4ctbs7CADN7tGusNsyjOm319Ao8usP1C27j0URuyIuw/YaYf+aA9+sCAwEAAaAAMA0GCSqGSIb3DQEBDQUAA4IBAQChtNuSQMtpLX3esiuQeXIZX0nxXLcBQhYEwpp2oAqMFP3+6GAn9gPe3HroFy9npQkfXFxIP9Mz67UMMoxAqceH27/8rHdWTNzSaoFeTHIXWt8HD3Ev16xnTYVWzvje4KIjJXSTJEJr88xjuYc/C3zmF0EP0xkDKjX/qobbUQcNOv3OhZPdtHOBXuLz3mhH6KXrlBO4L7AvnNWgoNgujJqAB030cICOuW97eXZebgt1G6ZGFJ9Wv5IOdKoACyPQL9KXfBMqtP1JdxsRg+JacN4gfRWikuaZt//n1PayxbdhHyx30bhhUeOSIWrLTEnnMnkSUD2Hx70Wd0dHc6ugyqhn
-----END CERTIFICATE REQUEST-----
```

**Comment by svenyonson** [comment]
OK, I'll dig into it and let you know

**Comment by cbaker6** [comment]
If you think you found something wrong in the framework, you can submit a PR with a failing test case (using the examples in the test file). That will make it easier for me to determine if/where the problem is.

**Comment by svenyonson** [comment]
Sounds good. Thanks Corey

**Comment by cbaker6** [comment]
It’s possible you are tryin a key/hash combination that macOS doesn’t like or if you are doing EC, your Mac doesn’t have Secure Enclave. Look in the test cases for https://github.com/cbaker6/CertificateSigningRequest/blob/523b7a35eb4725bc5419859a325f8c0b862c00b8/Tests/CertificateSigningRequestTests/CertificateSigningRequestTests.swift#L36

Also look at this note https://github.com/cbaker6/CertificateSigningRequest#macos

Lastly, make sure you are removing old keys when reusing the same tag https://github.com/cbaker6/CertificateSigningRequest/issues/14#issuecomment-620304226

**Comment by svenyonson** [comment]
I'll try to find some time to run the tests and/or create a reproducible case for you, but I'm under deadline at the moment. 
But, I was able to workaround the problem with this addition. (CSR is processed without problems).
`    public func buildCSRAndReturnString(_ publicKeyBits: Data, privateKey: SecKey, publicKey: SecKey?=nil) -> String? {

        guard var csrString = self.buildAndEncodeDataAsString(publicKeyBits,
                                                              privateKey: privateKey, publicKey: publicKey) else {
            return nil
        }
        
        var pos = 0
        var out = ""
        
        for char in csrString {
            if pos > 0 && (pos % 64) == 0 && char != "\n" {
                out += "\n"
            }
            out += "\(char)"
            pos += 1
        }
        
        csrString = out
        

        let formattedCSRString = String(format:"%@%@%@","-----BEGIN CERTIFICATE REQUEST-----\n", csrString, "\n-----END CERTIFICATE REQUEST-----\n")

        return formattedCSRString
    }`

**Comment by svenyonson** [comment]
This is the calling code. RSA 2048.
```
    // For now, we always create a new keypair when generating a CSR.
    private func createCSR() -> String? {
        
        // Preempt issues with existing keys, certs, identities (for this app). We might add a group key to limit the scope further, but for now it seems to work.
        emptyKeychain()
        
        let (potentialPrivateKey, potentialPublicKey) =
            self.generateKeysAndStoreInKeychain(keyAlgorithm, keySize: sizeOfKey,
                                                tagPrivateKey: KeyChain.tagPrivateKey,
                                                tagPublicKey: KeyChain.tagPublicKey)
        guard let privateKey = potentialPrivateKey,
            let publicKey = potentialPublicKey else {
                assert(potentialPrivateKey != nil, "Private key not generated")
                assert(potentialPublicKey != nil, "Public key not generated")
                return nil
        }

        let (potentialPublicKeyBits, potentialPublicKeyBlockSize) =
            self.getPublicKeyBits(keyAlgorithm,
                                  publicKey: publicKey, tagPublicKey: KeyChain.tagPublicKey)
        
        guard let publicKeyBits = potentialPublicKeyBits,
            potentialPublicKeyBlockSize != nil else {
                assert(potentialPublicKeyBits != nil, "Private key bits not generated")
                assert(potentialPublicKeyBlockSize != nil, "Public key block size not generated")
                return nil
        }
        
        // Generate CSR Data
        let csr = CertificateSigningRequest(commonName: commonName,
                                            organizationName: organizationName, organizationUnitName: organizationUnitName,
                                            countryName: countryName, stateOrProvinceName: stateOrProvinceName,
                                            localityName: localityName, emailAddress: emailAddress,
                                            description: description, keyAlgorithm: keyAlgorithm)
        // Build the CSR String
        let csrBuild = csr.buildCSRAndReturnString(publicKeyBits, privateKey: privateKey)
        if let csrWithHeaderFooter = csrBuild {
            print(csrWithHeaderFooter)
            assert(csrBuild!.contains("BEGIN"), "CSR string builder isn't complete")
        } else {
            assert(csrBuild != nil, "CSR with header not generated")
        }
        
        // Delete public key from keychain - https://developer.apple.com/forums/thread/69642
        deletePublicKeyFromKeychain(publicKey: publicKey)
        return csrBuild
    }
    

```

**Comment by svenyonson** [comment]
BTW, if it wasn't clear by the title, the parsing fails on macOS (node.js  server), but the CSR code that is causing the problem is on iOS.

**Comment by svenyonson** [comment]
I'm not experienced with xctest, but I just attempted to run the RSA2048 test on an iPhone 12 simulator.  

![image](https://user-images.githubusercontent.com/369966/105609497-f695ec80-5d66-11eb-93e8-8331cd0af95b.png)

**Comment by svenyonson** [comment]
I was able to run the macOS test successfully (same test as above), but I am unable to run the same test on the iOS simulator. My best guess at this point is that there is an iOS specific issue.

**Comment by svenyonson** [comment]
Corey, I believe I have found the problem. You need to add this option to the base64 encoding (which it probably defaults to on macOS): `lineLength64Characters`

https://developer.apple.com/documentation/foundation/nsdata/base64encodingoptions/1407872-linelength64characters

**Comment by svenyonson** [comment]
Ok, a new twist. 

This works:
```
        return buildData.base64EncodedString(options: .lineLength64Characters)

```

But this doesn't. I guess the percentEncoding negates the line length.
```
        return buildData.base64EncodedString(options: .lineLength64Characters).addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed)

```

**Comment by cbaker6** [comment]
Yeah that looks similar to https://github.com/cbaker6/CertificateSigningRequest/issues/8#issue-267801220

**Comment by svenyonson** [comment]
I'll stick with my simple, if awkward workaround as it won't do anything unless the newlines are missing

**Comment by cbaker6** [comment]
The code integration tests run on iOS and macOS so if you submit a PR, the CI will run the tests for you.
