### ISSUE TITLE
CSR Enhancement

### ISSUE THREAD

**Issue by chathuraasanka** [cbaker6/CertificateSigningRequest#45]
Need to add following Certificate Attributes to the CSR, 
- Key Usage
- Extend Key Usage 

Is there any function to add above attributes to the CSR
![MicrosoftTeams-image](https://user-images.githubusercontent.com/23569181/116647492-51f3fe00-a998-11eb-8ca8-322c6281e874.png)

**Comment by cbaker6** [comment]
This is a duplicate of #12 you should ask your question there.

**Comment by chathuraasanka** [comment]
Hi Corey,

I have found  the function, Can you please provide me a sample code how to add attribute to the CRS, I tried but it gives me an error.

**Comment by cbaker6** [comment]
I linked to what you should need in my previous comment

**Comment by LahiruChathuranga** [comment]
@cbaker6 

Hi, Can you provide me an example to do this? I saw that add attribute comment, but I could not add those things to CSR using it. Please.
