### ISSUE TITLE
Open SSL config

### ISSUE THREAD

**Issue by Hades2333** [cbaker6/CertificateSigningRequest#58]
Hello Corey, i use your library and my friend to couldn't decode csr, cause he has different open ssl config. Can i somehow change default open ssl config to custom file?

**Comment by Hades2333** [comment]
tags for your private and public keys must be unique every time you run the app

**Comment by cbaker6** [comment]
Not necessarily every time you run the app, but every time you want to change the public and private key. You should query tags you want to reuse, see here: https://github.com/cbaker6/CertificateSigningRequest/issues/14#issuecomment-620304226
