### ISSUE TITLE
EC key SHA1 oid size mismatch

### ISSUE THREAD

**Issue by fatsolow88** [cbaker6/CertificateSigningRequest#62]
let sequenceObjectSHA1WithECEncryption: [UInt8] =
    [0x30, 0x0A, 0x06, 0x07, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x01]

The second slot, 0x0A should be 0x09 instead since it occupied 9 slots only

**Comment by cbaker6** [comment]
Thanks @fatsolow88, I've created a PR with the fix
