### ISSUE TITLE
FAILED - CSR has an invalid signature. Key Size	WARNING (0 bits)

### ISSUE THREAD

**Issue by desertSniper87** [cbaker6/CertificateSigningRequest#63]
Hi, I am trying to generate private key and public key and save them in MAC's login keychain. Then I want to generate csr by using those private key public keys and ASN.1. I followed exactly what you have described. My csr is generated but it has invalid signature and the keysize showed 0. I have attached my csr informations in below pdf.

[csr.pdf](https://github.com/cbaker6/CertificateSigningRequest/files/11422287/csr.pdf)
My major files are attached here.
[csr.zip](https://github.com/cbaker6/CertificateSigningRequest/files/11422328/csr.zip)

**Comment by cbaker6** [comment]
Please see https://github.com/cbaker6/CertificateSigningRequest/issues/44#issuecomment-792413536
